# Generated by Django 3.0.7 on 2020-06-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skpcore', '0002_auto_20200615_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='husreglerform',
            name='text',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
