# Generated by Django 3.0.7 on 2020-06-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skpcore', '0003_auto_20200615_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='husreglerform',
            name='text',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
