# Generated by Django 3.0.7 on 2020-06-15 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skpcore', '0004_auto_20200615_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bruger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('data_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Senestenyt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nyt', models.TextField(max_length=1000, null=True)),
                ('bruger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skpcore.Bruger')),
            ],
        ),
    ]
