# Generated by Django 3.0.7 on 2020-06-15 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skpcore', '0005_bruger_senestenyt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='senestenyt',
            old_name='nyt',
            new_name='besked',
        ),
    ]
