# Generated by Django 3.0.7 on 2020-06-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skpcore', '0006_auto_20200615_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senestenyt',
            name='besked',
        ),
        migrations.AddField(
            model_name='senestenyt',
            name='blog_picture',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='senestenyt',
            name='blog_text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='senestenyt',
            name='postdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='senestenyt',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
