# Generated by Django 3.0.7 on 2020-06-15 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skpcore', '0007_auto_20200615_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senestenyt',
            name='blog_picture',
        ),
        migrations.RemoveField(
            model_name='senestenyt',
            name='blog_text',
        ),
        migrations.RemoveField(
            model_name='senestenyt',
            name='postdate',
        ),
        migrations.RemoveField(
            model_name='senestenyt',
            name='title',
        ),
        migrations.AddField(
            model_name='senestenyt',
            name='besked',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, null=True)),
                ('postdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('blog_picture', models.CharField(max_length=1000, null=True)),
                ('blog_text', models.CharField(max_length=1000, null=True)),
                ('bruger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skpcore.Bruger')),
            ],
        ),
    ]
