# Generated by Django 3.0.7 on 2020-06-15 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skpcore', '0008_auto_20200615_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogcomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bruger_pic', models.CharField(max_length=200, null=True)),
                ('comment', models.TextField(max_length=200, null=True)),
                ('postdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('bruger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skpcore.Bruger')),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blogcomment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skpcore.Blogcomment'),
        ),
    ]
