# Generated by Django 3.0.7 on 2020-06-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skpcore', '0009_auto_20200615_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='blogcomment',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blogcomment',
            field=models.ManyToManyField(null=True, to='skpcore.Blogcomment'),
        ),
    ]
