# Generated by Django 3.0.7 on 2020-06-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skpcore', '0010_auto_20200615_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='bruger_pic',
        ),
        migrations.AddField(
            model_name='bruger',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blogcomment',
            field=models.ManyToManyField(to='skpcore.Blogcomment'),
        ),
    ]
