# Generated by Django 3.0.7 on 2020-06-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skpcore', '0011_auto_20200615_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blogcomment',
            field=models.ManyToManyField(null=True, to='skpcore.Blogcomment'),
        ),
    ]
