# Generated by Django 3.0.5 on 2020-06-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skpcore', '0012_auto_20200615_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blogcomment',
            field=models.ManyToManyField(blank=True, to='skpcore.Blogcomment'),
        ),
    ]
