# Generated by Django 3.0.5 on 2020-06-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skpcore', '0014_infoform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='husreglerform',
            name='text',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='infoform',
            name='text',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
