# Generated by Django 3.0.7 on 2020-06-19 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skpcore', '0015_auto_20200615_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='blogcomment',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='blogpost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skpcore.Blogpost'),
        ),
    ]
