# Generated by Django 3.0.7 on 2020-06-19 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skpcore', '0016_auto_20200619_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='blogpost',
            new_name='blog',
        ),
    ]
